name: 'Pull Request Merge'
description: 'Wait for manual approval before merging a pull request'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
