name: CI/CD Pipeline2

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install pytest-cov
        run: poetry add pytest-cov -G --dev 

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=.

      - name: Verify coverage
        id: verify-coverage
        run: |
          poetry run coverage report --fail-under=80 

  require-approval:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: HoracioBiancardi
          minimum-approvals: 1

  merge-release-to-main:
    runs-on: ubuntu-latest
    needs: require-approval

    steps:
      - uses: actions/checkout@master

      - name: Merge release -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge release into main
          github_token: ${{ secrets.GITHUB_TOKEN }}
