name: CI/CD Pipeline2

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install pytest-cov
        run: poetry add --dev pytest-cov

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=./ --cov-report=xml

      - name: Verify coverage
        id: verify-coverage
        run: |
          poetry run coverage report --fail-under=80 || echo "coverage_failed=true" >> $GITHUB_ENV

      - name: Upload coverage report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

      - name: Save coverage check result
        run: |
          echo "coverage_failed=${{ env.coverage_failed }}" > coverage_check.txt
        if: always()

      - name: Upload coverage check result
        uses: actions/upload-artifact@v2
        with:
          name: coverage-check
          path: coverage_check.txt

  code_review:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Create a pull request to main
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Merge release branch into main
          branch: main
          title: 'Merge release branch into main'
          body: 'This PR merges the release branch into main after passing all checks.'
          delete-branch: true

#  require-approval:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Download coverage check result
#        uses: actions/download-artifact@v2
#        with:
#          name: coverage-check
#
#      - name: Read coverage check result
#        id: read-coverage-check
#        run: |
#          coverage_failed=$(cat coverage_check.txt)
#          echo "coverage_failed=$coverage_failed" >> $GITHUB_ENV
#
#      - uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ github.TOKEN }}
#          approvers: HoracioBiancardi
#
#  merge-release-to-main:
#    runs-on: ubuntu-latest
#    needs: require-approval
#
#    steps:
#      - uses: actions/checkout@master
#
#      - name: Merge release -> main
#        uses: devmasx/merge-branch@master
#        with:
#          type: now
#          target_branch: main
#          message: Merge release into main
#          github_token: ${{ secrets.GITHUB_TOKEN }}
